### ISSUE TITLE
Change CosmosDB provisioning to ARM Template

### ISSUE THREAD

**Issue by k-miyake** [intelligent-retail/smart-store#33]
I would like to change the method of provisioning containers of CosmosDB to ARM Template.
In addition, create lease container in one database.

reference: https://docs.microsoft.com/ja-jp/azure/cosmos-db/manage-sql-with-resource-manager
need change: https://github.com/intelligent-retail/smart-store/blob/2806f6f178ae75aa9633452584f883c7e9a9a4c2/src/stock-service/StockService.StockProcessor/ChangeFeedFunction.cs#L21

**Comment by dzeyelid** [comment]
@k-miyake  I tried that create a cosmosDB's collection as leases manually before the change feed function run. But this updates could not fix the problem that first several operations don't run the change feed. 😢

**Comment by dzeyelid** [comment]
I found I forgot creating the main CosmosDB's database for stock service. After adding the creation, I could solve the problem!
