### ISSUE TITLE
[Request to fix] Code comment was garbled [StockService]

### ISSUE THREAD

**Issue by yoshifumi-okada** [intelligent-retail/smart-store#38]
Hi, I would like you to fix following issues. Thank you.

[Current] Following code commenting of Developer was garbled and hard to read as OSS. In here You can see Japanese sentence is garbled in comment line.
<https://github.com/intelligent-retail/smart-store/blob/master/src/stock-service/StockService.StockProcessor/ChangeFeedFunction.cs>

[Expectation]
To fix it, and we can read what developer saying for internal processor of coding.

**Comment by k-miyake** [comment]
@yoshifumi-okada 
Thank you for your feedback. The issue was solved by #40 .
