### ISSUE TITLE
Compatible dotnetCore and AzureSDK

### ISSUE THREAD

**Issue by yoshifumi-okada** [intelligent-retail/smart-store#39]
Hi, Team

Could you please fix this <smart-store/src/pos-service/PosService/POSService.csproj> to adapt the compatible with template code.

 <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />

Regards,
Yoshi

**Comment by dzeyelid** [comment]
@yoshifumi-okada Thanks for raising this issue! We fixed this issue.
